drop user bme cascade;
create user bme identified by bme_123 quota 100M on users;
 GRANT CREATE DIMENSION TO bme;
 GRANT CREATE TABLE TO bme;
 GRANT CREATE JOB TO bme;
 GRANT CREATE TYPE TO bme;
 GRANT CREATE OPERATOR TO bme;
 GRANT CREATE VIEW TO bme;
 GRANT CREATE INDEXTYPE TO bme;
 GRANT CREATE CLUSTER TO bme;
 GRANT CREATE PROCEDURE TO bme;
 GRANT CREATE SESSION TO bme;
 GRANT CREATE MATERIALIZED VIEW TO bme;
 GRANT CREATE SEQUENCE TO bme;
 GRANT DEBUG CONNECT SESSION TO bme;
 GRANT CREATE TRIGGER TO bme;
 GRANT CREATE SYNONYM TO bme;

/*
create apex workspace and users on this schema
*/
